services:
  jenkins:
    build: .
    container_name: jenkins-cicd
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./:/var/jenkins_home/workspace/Parcial_AZ
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: